version: '3.8'
services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'strava'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'lars'
      MYSQL_PASSWORD: 'lars'
    container_name: "mysql"
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - strava-db:/var/lib/mysql
volumes:
  strava-db: